"""The fade memory -- dual-SSM recall that degrades from verbatim to gist.

Implements the Stage-1 fade architecture (``docs/fade-architecture.md``, task #34):
an SSM memory that recalls recent content verbatim and degrades to the gist of
older content as the state compresses over a streamed session. The fade EMERGES
from real state degradation (the SSM-A vector channel decaying under the
recurrence), not a policy switch on wall-clock age.

The two legs (validated by the two no-training gating probes, both PASS):
  - SSM-A (the fade leg): a 384-d bge-space vector-carry channel. Each ingested
    chunk writes its frozen ``bge(chunk)`` vector into the channel; the recurrence
    decays older vectors as newer ones stream in. The faded state is read as a
    retrieval query. THE FADE LIVES HERE -- in the vector's graceful decay
    (probe #32: exact -> sibling/gist -> unrelated, tunable by decay). No text is
    decoded from the state (decoding is the 3x-disproven path).
  - SSM-B (the voice leg): the token-LM ``SSMLanguageModel``. Given a retrieved
    blurb (a short text excerpt), EXPANDS it into fuller recall via continuation
    (probe #31: the token-LM is the voice, not a fade substrate -- only ~1-2
    tokens of verbatim then prior-only).

The router (the keystone): because SSM-A's state IS a blend of bge vectors (it
lives in the same 384-d space as the anchors), the recoverability signal is FREE
-- ``e(i,t) = 1 - cos(state_t, bge(anchor_i))`` is both the retrieval score AND
the forgetting signal. No ridge decoder, no trained head. This is the Sec-6.1
recovery-decoder recipe (``e = ||D(state) - anchor||^2``) realized directly by
cosine, because the channel is already in the anchor's space -- the payoff of the
bge-space channel decision (Option 2). Probe #32 showed this cosine tracks the
fade: 1.0 (N=0) -> 0.95 (N=1) -> ~0.8 plateau (the tip-of-tongue floor).

The four regimes (selected per-anchor by ``e(i,t)`` at recall time):
  1. low e -- still in the state -> VERBATIM from the ring. The ring is a recency
     window that gives true verbatim independent of the state's fade (the
     architecture's "the ring gives true verbatim for the ring window regardless").
     Gate: anchor in the ring, OR ``cos >= cos_ring`` (state still fresh).
  2. medium e -- degraded but residual -> Regime 3 behavior (retrieve + expand).
     The Transformer fill-holes readout (``CrossSlotTransformerZHead``) is a
     deprioritized Stage-2 layer (probe #31: the token-LM state residual is thin);
     ``regime2_enabled=False`` by default, so medium-e falls through to Regime 3.
  3. high e, vector still retrievable (``cos >= cos_gist``) -- gone from state,
     address survives -> the faded state retrieves a (possibly sibling) blurb ->
     SSM-B expands it. Fuzzy gist.
  4. high e, vector too faded (``cos < cos_gist``) -> TRULY FORGOTTEN -> the system
     says "forgotten" rather than confabulating. The graceful floor
     (metacognition / tip-of-tongue).

Isolated module: no orchestrator/runtime/serve IMPORTS (the wiring flows one way --
``runtime.build_ponder`` constructs and injects a ``FadeMemory``; this module never
imports the serve path). The voice (SSM-B) and the embedder (bge) are injected
(``Voice`` / ``Embedder`` protocols) so the unit test runs CPU-only with synthetic
vectors and a test-double voice; production wires the real token-LM
(``load_token_lm_voice``) or a pretrained Mamba3 LM (``load_mamba3_voice``) +
the shared bge embedder (reused from ``build_ponder``).
"""

from __future__ import annotations

from collections import deque
from dataclasses import dataclass
from typing import TYPE_CHECKING, Optional, Protocol

import numpy as np

if TYPE_CHECKING:
    # ``StructuredGist`` is defined in ``gister.py`` (a sibling). Imported only
    # under TYPE_CHECKING so ``fade`` stays import-clean (no Bonsai/HTTP pulled
    # in at import time -- the unit tests run CPU-only without the Bonsai
    # server). ``consolidate`` takes it but the annotation is a string (future
    # annotations), so this never evaluates at runtime.
    from .gister import StructuredGist

# Regime labels (integers so they serialize trivially).
REGIME_VERBATIM = 1     # ring / state-fresh -> exact text
REGIME_FILL = 2         # Transformer fill-holes (Stage 2, deprioritized)
REGIME_GIST = 3         # faded state retrieves a blurb -> SSM-B expands
REGIME_FORGOTTEN = 4    # tip-of-tongue floor -> "forgotten" marker
# Cross-turn Mamba3 carry (exp #4): a within-window recall generated by cueing
# the carried conversation state. NOT a BlurbStore anchor (anchor_id = -1); the
# free cosine router does not produce it (no bge-vs-state signal -- Mamba3's
# token state is not a bge vector). Sourced from ``Mamba3Voice.recall_from_carry``
# when ``FadeConfig.voice_carry`` is on. Additive to the SSM-A regime path.
REGIME_CARRY = 5

# Human-readable regime names (kept here next to the labels so callers -- the
# orchestrator, the eval scripts -- do not each redefine the mapping; the eval
# scripts' own ``REGIME_NAME`` mirror this).
REGIME_NAME: dict[int, str] = {
    REGIME_VERBATIM: "verbatim",
    REGIME_FILL: "fill",
    REGIME_GIST: "gist",
    REGIME_FORGOTTEN: "forgotten",
    REGIME_CARRY: "carry",
}


def format_fade_block(recalls: list[dict], max_tokens: int = 0) -> str:
    """Render fade recalls as a ``[FADE MEMORY]`` block for the LLM context.

    Takes the dict shape the orchestrator's RECALL seam builds
    (``{anchor_id, regime, regime_name, cos, cos_q, content, blurb}``). Lists only
    CONTENT-BEARING recalls:

    - R1 (verbatim): the recent exact text.
    - R3 (gist): the anchor's blurb (verbatim when ``voice is None`` -- Phase B;
      a paraphrase once the token-LM voice leg is wired).

    R4 (forgotten) is intentionally SKIPPED: it is a SIGNAL for a future long-term-
    memory pull (mechanism TBD -- explicit tool call vs background fulfillment), not
    LLM-facing content. The forgotten material is simply absent from the block -- the
    gradient "exact -> gist -> (gone)" reads naturally, like a human who does not
    enumerate what they have forgotten. R4 stays in ``fade_recalls`` (observability +
    the signal the future pull consumes).

    Returns ``""`` when no content-bearing recalls are present (so the block is
    omitted entirely -- no empty header). Bounded by the seam's ``top_k`` /
    ``blurb_chars`` caps (the recalls arrive already capped).

    A4 budget cascade (``max_tokens > 0``): the block sits OUTSIDE the chunker's
    context budget, so this is the only place it is bounded. When the rendered
    block exceeds ``max_tokens`` (``len//4`` estimate, the codebase convention),
    recalls are dropped until it fits: most-faded first -- R3 (gist) before R1
    (verbatim), R4 already excluded -- and within a regime the lowest ``cos_q``
    (prompt relevance) first. ``max_tokens=0`` (default) = no budget = the block
    is byte-identical to pre-A4. When the block fits, no drop occurs -> also
    byte-identical. Kept recalls preserve their input order (the retriever's
    relevance order).
    """
    header = ("[FADE MEMORY -- your fading working memory of this conversation]\n"
              "(Recent exchanges are recalled exactly; older ones are given as a "
              "fading gist. What has fully faded is not listed.)")

    def _line(regime: int, content: str, r: dict) -> str:
        if regime == REGIME_VERBATIM:
            return f"[verbatim, recent] {content}"
        if regime == REGIME_GIST:
            return f"[gist, fading] {content}"
        if regime == REGIME_FILL:
            return f"[fill, reconstructed] {content}"
        if regime == REGIME_CARRY:
            # Within-window recall from the carried Mamba3 conversation state
            # (exp #4: cross-turn carry = in-context recall, to the ~2048-token
            # training-ctx ceiling). Generated continuation, not stored verbatim.
            return f"[carry, in-context] {content}"
        return f"[{r.get('regime_name') or regime}] {content}"

    # Content-bearing items in INPUT order (preserves the retriever's relevance
    # order for the kept recalls -> byte-identical when none are dropped).
    items: list[tuple[int, str, dict]] = []
    for r in recalls:
        regime = r.get("regime")
        if regime == REGIME_FORGOTTEN:
            continue  # R4 is a signal, not LLM content (see docstring).
        content = (r.get("content") or "").strip()
        if not content:
            continue
        items.append((regime, content, r))
    if not items:
        return ""

    def _render(its: list[tuple[int, str, dict]]) -> str:
        return header + "\n" + "\n".join(_line(reg, c, r) for reg, c, r in its)

    block = _render(items)

    # A4: regime-cascade drop when over budget. Highest regime first (R3=3 >
    # R2=2 > R1=1; R4 already excluded); within a regime, lowest cos_q (max of
    # ``-cos_q``) first. Re-render after each drop. Terminates: ``items``
    # shrinks each iteration. The carried recall (REGIME_CARRY) is the single
    # most valuable within-window recall -- it gets the LOWEST drop priority
    # (mapped to -1) so it is never dropped while any R3/R1 remains.
    if max_tokens > 0:
        while items and (len(block) // 4) > max_tokens:
            victim = max(range(len(items)),
                         key=lambda i: (
                             items[i][0] if items[i][0] != REGIME_CARRY else -1,
                             -items[i][2].get("cos_q", 0.0)))
            items.pop(victim)
            block = _render(items)
        # Budget too tight for any recall -> omit the block entirely (no empty
        # header -- mirrors the no-items contract above). Unreachable at the
        # inert default 1024 (~750-token block); only a very tight config drops
        # every recall, and a header-only block would mislead the LLM.
        if not items:
            return ""
    return block


class Embedder(Protocol):
    """``texts -> list of dim-d float vectors`` (bge-small-en-v1.5, 384-d, frozen)."""

    def encode(self, texts: list[str]) -> list[list[float]]: ...


class Voice(Protocol):
    """SSM-B: expand a retrieved blurb into fuller recall via continuation."""

    def expand(self, blurb: str, max_new_tokens: int) -> str: ...


class CarryVoice(Protocol):
    """A ``Voice`` that also keeps a per-conversation carried state across turns.

    The cross-turn carry leg (exp #4). ``ingest_turn`` is the sole writer of the
    carried state (forwards one turn's tokens, no decode); ``recall_from_carry``
    is read-only (clones the state, cues it, decodes a continuation). Only
    ``Mamba3Voice`` implements this today; ``TokenLMVoice`` and the passthrough
    (``voice is None``) do not, so ``FadeMemory`` guards every call on
    ``hasattr(self.voice, "ingest_turn")`` -- a non-carry voice makes carry a
    no-op, byte-identical to ``voice_carry=False``.
    """

    def ingest_turn(self, text: str, max_tokens: int = 2048) -> int: ...
    def recall_from_carry(self, cue: str, max_new_tokens: int = 64) -> str: ...
    def reset_carry(self) -> None: ...


@dataclass
class FadeConfig:
    """Fade-memory hyperparameters. Defaults calibrated from probe #32 and the
    cross-domain eval (``scripts/eval_fade_cross_domain.py``; see ``cos_gist``).

    ``decay``: the SSM-A EWMA decay (the fade timescale). 0.99 -> ~8-16-step
    gist window (probe #32). ``cos_ring``/``cos_gist``: the regime boundaries on
    the free cosine router. ``ring_capacity``: the recency verbatim window.
    ``blurb_chars``: max chars of chunk text stored as the blurb (a gist-sized
    excerpt -- the content seed SSM-B expands). ``expand_tokens``: SSM-B
    continuation length for a gist. ``regime2_enabled``: the Transformer
    fill-holes readout (Stage 2, deprioritized per probe #31).

    ``voice_carry``: the cross-turn Mamba3 carry leg (exp #4 -- ADDITIVE, default
    OFF). When True and the voice is a ``CarryVoice`` (``Mamba3Voice``), each
    ``ingest`` also forwards the turn through a per-conversation carried
    ``InferenceParams`` (the within-window conversation state), and ``recall``
    prepends a ``REGIME_CARRY`` recall generated by cueing that state. This makes
    the cross-turn carry finding real in serve; A/B-able against the SSM-A regime
    path. ``voice_carry_max_tokens``: the carried-state budget (default 2048 = the
    Mamba3-SISO training-ctx ceiling from ``mamba3-recall-probe-result``; beyond it
    carry degrades together with continuous and WaveDB takes over). ``voice_carry
    _recall_tokens``: the decode length for a carried recall (default 64, same as
    ``expand_tokens``). Only ``Mamba3Voice`` implements carry today; ``TokenLMVoice``
    /passthrough skip it (``FadeMemory`` guards on ``hasattr``). Byte-identical to
    flag-off when ``voice_carry`` is False (the project default-OFF pattern).
    """

    decay: float = 0.99
    write_gate: float = 1.0
    cos_ring: float = 0.95      # cos >= this (or anchor in ring) -> Regime 1
    # cos >= this (and not R1) -> Regime 3 (gist); below it -> Regime 4 (forgotten).
    # Calibrated for REAL bge-small-en-v1.5 by the cross-domain eval
    # (scripts/eval_fade_cross_domain.py): bge-small has a HIGH cosine floor --
    # same-domain ~0.6, cross-domain ~0.37 -- so the threshold must sit BETWEEN
    # them to separate "same topic -> fuzzy gist (R3)" from "different topic ->
    # forgotten (R4)". 0.40 (probe #32's 0.30 was calibrated on the synthetic test
    # embedder whose cross-doc floor is ~0.01, far below real bge's ~0.37, so 0.30
    # never reached R4 on real bge). The unit tests override this (their synthetic
    # embedder has a ~0.01 cross-doc floor, so they use 0.15-0.20).
    cos_gist: float = 0.40
    ring_capacity: int = 32     # recent anchors kept verbatim
    blurb_chars: int = 600      # max chars of chunk text stored as the blurb
    expand_tokens: int = 64     # SSM-B continuation length for a gist
    regime2_enabled: bool = False  # Transformer fill-holes (Stage 2, off)
    # A4: token budget on the rendered ``[FADE MEMORY]`` block. The block sits
    # OUTSIDE the chunker's context budget (it is prepended to ``user_content``
    # after the chunked context is built), so without this it escapes every
    # cap. Inert at current defaults (top_k=5 x blurb_chars=600 ~ 750 tokens <
    # 1024). When the block overflows, ``format_fade_block`` drops recalls
    # regime-cascade: R3 (gist) before R1 (verbatim) -- R4 is already skipped at
    # render; within a regime, lowest ``cos_q`` (prompt relevance) first. 0 = no
    # budget = byte-identical to pre-A4. ~25% of the 4000-token context budget.
    fade_block_max_tokens: int = 1024
    # Cross-turn Mamba3 carry (exp #4, additive, default OFF -- see docstring).
    voice_carry: bool = False
    voice_carry_max_tokens: int = 2048  # Mamba3-SISO training-ctx ceiling
    voice_carry_recall_tokens: int = 64  # decode length for a carried recall
    # Cue engineering (exp #4 follow-on, default IDENTITY). A ``str.format``
    # template applied to the cue before ``recall_from_carry``: the 443M is a
    # BASE (non-instruct) LM ([[mamba3-recall-probe-result]]), and the live A/B
    # showed variable completion (a needle on one turn, a degenerate loop on the
    # next) when cued with the raw ``user_prompt``. A completion-style cue (e.g.
    # ``" {cue}\nA:"``) can elicit the carried content better than a raw
    # question. The template receives ``{cue}`` = the user_prompt. Default
    # ``"{cue}"`` is IDENTITY -> byte-identical (the recall path skips the
    # ``format`` call on the default so the hot path is untouched).
    voice_carry_cue_template: str = "{cue}"
    # The collapse (exp #4 follow-on, additive, default OFF). When True, the SSM-A
    # ingest/recall path is SUPPRESSED and the carried Mamba3 state is the SOLE
    # within-window cross-turn memory; beyond the ~2048-token training-ctx ceiling
    # is WaveDB's job (the orchestrator's retriever -- a separate path this memory
    # never owned). The keystone premise ([[pondr-fade-architecture-router]]: "Mamba3
    # has zero cross-context memory") is FALSIFIED by exp #4: carry IS in-context
    # recall, lossless to the ceiling, so SSM-A (bge EWMA + BlurbStore + the cosine
    # router + R1/R3/R4 cascade) is REDUNDANT within the window. The cosine router
    # is DROPPED, not redesigned: it exists only because SSM-A's state is a bge
    # vector you can ``cos(state, bge(anchor))``; with SSM-A gone there is nothing to
    # route -- the within-window recall is UNCONDITIONAL carry (cue + decode one
    # continuation), and beyond-window is the orchestrator's retriever. Requires
    # ``voice_carry`` + a ``CarryVoice`` (``Mamba3Voice``); ``build_ponder`` /
    # ``serve_ponder`` auto-enable carry under collapse and require the mamba3
    # backend. Tradeoff: recall BREADTH narrows from top-k routed anchors to ONE
    # ~64-token carry continuation -- the thing to evaluate (cue engineering
    # addresses recall QUALITY; a future multi-cue extension could address breadth).
    # The SSM-A machinery (``VectorCarrySSM`` / ``BlurbStore`` / the ring / the
    # regime cascade / consolidation) stays INTACT for the OFF baseline -- collapse
    # disables it, does not delete it -- so the dual-SSM vs collapse is A/B-able.
    # Byte-identical to today when False (the project default-OFF pattern).
    collapse: bool = False


# ----------------------------------------------------------------------- SSM-A
class VectorCarrySSM:
    """SSM-A: a 384-d bge-space vector-carry channel (the fade leg).

    The no-training stand-in validated by probe #32: an exponentially-weighted
    moving average of chunk bge vectors,

        state_p = decay * state_{p-1} + write_gate * bge(chunk_p),   state_0 = 0

    so the anchor at stream position ``i`` contributes ``decay**N *
    bge(chunk_i)`` to ``state_{i+N}``. The fade is NOT "the vector shrinks"
    (cosine retrieval is scale-invariant -- the probe's read-only control stayed
    100% exact forever); it is the recurrence OVERWRITING the slot with newer
    chunk vectors, so the query drifts anchor -> recent-chunk blend -> unrelated.

    Structured to upgrade to a trained ``SelectiveSSM`` with selective gating
    (write only important chunks, preserve others) -- the probe's "exact only at
    N=0" is the EWMA's conservative lower bound; selective gating should EXTEND
    the exact window. That upgrade is a Stage-2 follow-on (a subclass overriding
    ``step``); the EWMA is the validated substrate for Stage 1.
    """

    def __init__(self, dim: int, decay: float, write_gate: float = 1.0) -> None:
        self.dim = int(dim)
        self.decay = float(decay)
        self.write_gate = float(write_gate)
        self._state = np.zeros(self.dim, dtype=np.float32)

    def step(self, bge_vec: np.ndarray) -> np.ndarray:
        """Write one chunk's bge vector into the channel; return the new state."""
        v = np.asarray(bge_vec, dtype=np.float32).reshape(-1)
        if v.shape[0] != self.dim:
            raise ValueError(f"bge_vec length {v.shape[0]} != dim {self.dim}")
        self._state = self.decay * self._state + self.write_gate * v
        return self._state

    def state(self) -> np.ndarray:
        """The raw (unnormalized) ``dim``-d channel state at the current step."""
        return self._state

    def query(self) -> np.ndarray:
        """The state L2-normalized as a retrieval query.

        float64 norm for underflow-safety at extreme ``decay**N`` (probe #32's
        control fix: a float32 norm squares ~1e-29 components into 0 at
        decay=0.5, N>=96, leaving the query un-normalized). The FADE path (state
        O(1)) is unaffected; the safety matters for the read-only control and for
        very long fast-decay streams.
        """
        s64 = self._state.astype(np.float64)
        nrm = float(np.linalg.norm(s64))
        if nrm == 0.0:
            nrm = 1.0
        return (s64 / nrm).astype(np.float32)

    def reset(self) -> None:
        self._state = np.zeros(self.dim, dtype=np.float32)


# ------------------------------------------------------------------ blurb store
class BlurbStore:
    """External store of ``(bge(chunk), blurb_text)`` keyed by anchor_id.

    The bridge: blurbs are stored at ingestion (the chunk's text, gist-sized),
    keyed by the chunk's bge vector. Retrieval is cosine against the stored bge
    vectors -- the same ``corpus @ q`` the probe validated. ``add`` L2-normalizes
    the bge (cosine is scale-invariant, so the stored vector and the SSM-A query
    share a convention); ``retrieve(q)`` returns the top-k ``(anchor_id, cos,
    text)``. In-memory numpy: the architecture's "external store" is satisfied by
    keeping the blurb OUT of the SSM state (it is not decoded from the state);
    persistence to WaveDB is a follow-on, not a Stage-1 need.
    """

    def __init__(self, dim: int) -> None:
        self.dim = int(dim)
        self._ids: list[int] = []
        self._vecs: list[np.ndarray] = []     # L2-normalized [dim] fp32
        self._texts: list[str] = []
        self._index: dict[int, int] = {}      # anchor_id -> row
        self._matrix: Optional[np.ndarray] = None  # [N, dim] rebuilt lazily
        # Structured-gist fact sidecar (the consolidation loop, see
        # ``FadeMemory.consolidate``). Empty for every non-consolidated anchor;
        # ``facts(id)`` returns [] when absent. Staged here for the future
        # R4 -> long-term-memory pull (the ``fact_sink`` consumes it).
        self._facts: dict[int, list[dict]] = {}

    @staticmethod
    def _normalize(v: np.ndarray) -> np.ndarray:
        v64 = np.asarray(v, dtype=np.float64).reshape(-1)
        nrm = float(np.linalg.norm(v64))
        if nrm == 0.0:
            nrm = 1.0
        return (v64 / nrm).astype(np.float32)

    def add(self, anchor_id: int, bge_vec: np.ndarray, text: str) -> None:
        """Store one chunk's blurb keyed by its (normalized) bge vector."""
        vn = self._normalize(bge_vec)
        if vn.shape[0] != self.dim:
            raise ValueError(f"bge_vec length {vn.shape[0]} != dim {self.dim}")
        self._index[anchor_id] = len(self._ids)
        self._ids.append(anchor_id)
        self._vecs.append(vn)
        self._texts.append(text)
        self._matrix = None  # invalidate the cached retrieval matrix

    def _mat(self) -> Optional[np.ndarray]:
        if self._matrix is None and self._vecs:
            self._matrix = np.stack(self._vecs, axis=0)  # [N, dim]
        return self._matrix

    def retrieve(self, query: np.ndarray, k: int = 5) -> list[tuple[int, float, str]]:
        """Top-k ``(anchor_id, cos, text)`` by cosine of ``query`` against the
        stored bge vectors, best first. ``query`` is L2-normalized here."""
        mat = self._mat()
        if mat is None or len(self._ids) == 0:
            return []
        q = self._normalize(query)
        sims = mat @ q  # [N] cosine (both normalized)
        n = len(sims)
        k = max(0, min(k, n))
        if k == 0:
            return []
        # argpartition for top-k, then sort those k by score descending.
        part = np.argpartition(-sims, k - 1)[:k]
        order = part[np.argsort(-sims[part])]
        return [(self._ids[i], float(sims[i]), self._texts[i]) for i in order]

    def vector(self, anchor_id: int) -> Optional[np.ndarray]:
        """The stored L2-normalized bge for ``anchor_id`` (for the router's
        per-anchor cosine). None if not present."""
        i = self._index.get(anchor_id)
        return None if i is None else self._vecs[i]

    def text(self, anchor_id: int) -> Optional[str]:
        i = self._index.get(anchor_id)
        return None if i is None else self._texts[i]

    def facts(self, anchor_id: int) -> list[dict]:
        """The structured-gist fact sidecar for ``anchor_id`` (relations +
        state_assertions). Empty list when the anchor has not been consolidated
        or has no extracted facts."""
        return self._facts.get(anchor_id, [])

    def update(self, anchor_id: int, new_vec: np.ndarray, new_text: str,
               facts: Optional[list[dict]] = None) -> None:
        """Re-key an anchor IN PLACE: replace its bge vector + blurb text (and
        optionally stage a facts sidecar). Used by ``FadeMemory.consolidate`` to
        turn a fading verbatim anchor into its structured gist -- the embed
        handle becomes ``bge(narrative)`` and the recalled blurb becomes the
        narrative (the maximem_synap_sdk cache-replacement semantics: the new
        summary REPLACES the cached fields). Invalidates the retrieval matrix so
        the next ``retrieve`` sees the new vector. Raises ``KeyError`` if the
        anchor is unknown (consolidation never targets a missing anchor)."""
        i = self._index[anchor_id]
        vn = self._normalize(new_vec)
        if vn.shape[0] != self.dim:
            raise ValueError(f"new_vec length {vn.shape[0]} != dim {self.dim}")
        self._vecs[i] = vn
        self._texts[i] = new_text
        if facts is not None:
            self._facts[anchor_id] = facts
        self._matrix = None  # invalidate the cached retrieval matrix

    def __len__(self) -> int:
        return len(self._ids)


# --------------------------------------------------------------------- the voice
class TokenLMVoice:
    """SSM-B: the token-LM expands a retrieved blurb via continuation.

    Wraps the trained ``SSMLanguageModel`` (``pondr-token-lm-ssm-result``). Given
    a blurb (a short text excerpt), encodes it as a prompt and autoregressively
    continues via ``generate`` -- which primes the recurrent state with the
    prompt in one forward pass, then steps, so the state actually carries the
    blurb (the point of the LM build). Research substrate; production swaps in
    the serving LLM as the voice.
    """

    def __init__(self, model, tokenizer, device: str = "cpu",
                 temperature: float = 0.7, top_k: int = 40) -> None:
        self.model = model
        self.tokenizer = tokenizer
        self.device = device
        self.temperature = float(temperature)
        self.top_k = int(top_k)

    def expand(self, blurb: str, max_new_tokens: int) -> str:
        import torch  # lazy: keeps the module importable without torch for tests

        ids = self.tokenizer.encode(blurb)
        if not ids:
            return blurb
        prompt = torch.tensor([ids], dtype=torch.long, device=self.device)
        out = self.model.generate(prompt, max_new_tokens,
                                  self.temperature, self.top_k)  # [1, seq+new]
        new_ids = out[0].tolist()[len(ids):]
        return self.tokenizer.decode(new_ids)


def load_token_lm_voice(checkpoint_path: str, tokenizer_path: str,
                         device: str = "cpu", temperature: float = 0.7,
                         top_k: int = 40) -> TokenLMVoice:
    """Load the trained token-LM as the SSM-B voice. Lazy torch import.

    ``checkpoint_path`` / ``tokenizer_path`` are the token-LM ckpt + tokenizer
    (``data/token_lm/...``; see ``pondr-token-lm-ssm-result``). The model is
    frozen (``eval()``) -- the voice expands, it does not train.

    ``device`` accepts ``"auto"`` (resolve to cuda if available, else cpu), like
    the other model loaders. ``torch.load`` and ``Module.to`` do NOT accept
    ``"auto"``, so it is resolved here and the checkpoint is always restored to
    CPU first (``map_location="cpu"``) then moved to the resolved device --
    mirrors ``load_backbone``."""
    import torch

    from .token_lm import LMConfig, SSMLanguageModel
    from .tokenizer_ import train_or_load_tokenizer

    if device == "auto":
        device = "cuda" if torch.cuda.is_available() else "cpu"
    ckpt = torch.load(checkpoint_path, map_location="cpu", weights_only=False)
    cfg = LMConfig(**ckpt["config"])
    model = SSMLanguageModel(cfg).to(device=device, dtype=torch.float32)
    model.load_state_dict(ckpt["model"])
    model.eval()
    tok = train_or_load_tokenizer(iter([]), tokenizer_path, vocab_size=cfg.vocab)
    return TokenLMVoice(model, tok, device, temperature, top_k)


# ----------------------------------------------------------- Mamba3 voice leg
def _bundled_tcc() -> Optional[str]:
    """Path to the triton-windows bundled TinyCC compiler, if present.

    ``triton-windows``'s ``get_cc()`` (``triton/runtime/build.py``) prefers an
    env-MSVC ``cl`` that is too old for ``/std:c11`` over the bundled TinyCC
    (``tcc.exe``, C11-capable), which breaks the Mamba3 Triton SISO JIT on this
    Windows dev box. Setting ``CC=<tcc>`` forces TinyCC and unblocks the JIT.
    See ``mamba3-siso-local-inference-works``. Returns ``None`` when triton is
    not installed or the bundled compiler is absent (non-Windows / no
    triton-windows) -- the caller must then export ``CC`` manually.

    Locates tcc via the triton package itself first (reliable for ``--user``
    installs, where ``sysconfig.get_paths()['platlib']`` is the SYSTEM
    site-packages and misses the ``--user`` triton), then falls back to the
    standard site-packages dirs.
    """
    import os
    import site
    import sysconfig

    candidates: list[str] = []
    try:
        import triton  # noqa: F401 -- located, not used
        candidates.append(os.path.join(os.path.dirname(triton.__file__),
                                       "runtime", "tcc", "tcc.exe"))
    except ImportError:
        pass
    for base in [sysconfig.get_paths()["platlib"], site.getusersitepackages(),
                 *site.getsitepackages()]:
        candidates.append(os.path.join(base, "triton", "runtime", "tcc",
                                       "tcc.exe"))
    for p in candidates:
        if os.path.exists(p):
            return p
    return None


def _mamba3_siso_carry_forward(self, u, seq_idx=None, cu_seqlens=None,
                               inference_params=None):
    """Carry-correct ``Mamba3.forward`` for the SISO checkpoints on this box.

    Stock ``Mamba3.forward`` never threads the cached recurrent state back into
    the Triton SISO kernel: ``Input_States`` is hardcoded ``None`` and the resume
    path (``seqlen_offset > 0``) routes to ``self.step()``, which asserts the CuTe
    ``mamba3_step_fn`` -- ``None`` on this pure-python install (no
    nvidia-cutlass-dsl / quack-kernels; see ``mamba3-cuda-build-fails``). So the
    state is written to the ``InferenceParams`` cache and never read back: naive
    cross-call usage is silently stateless, correct usage crashes.

    This forward is byte-identical to stock EXCEPT it drops the
    ``seqlen_offset > 0 -> self.step()`` early return and threads the cached
    state into ``mamba3_siso_combined``'s ``Input_States`` when resuming (the K
    cache holds ``(B,1,H,d_state)``; the kernel wants ``(B,H,d_state)`` so it is
    squeezed). ``return_final_states=True`` whenever a cache is present so the
    next resume can seed from this call's final state. The combined kernel uses
    EXACT math (no ``cos_approx`` / ``sin_approx`` / ``sigmoid_approx`` /
    ``tanh_approx``), so a length-1 decode via this path is exact and O(n) -- the
    correct local decode (the Triton ``mamba3_siso_step`` kernel accumulates
    approximation error and collapses to a repetition attractor within a few
    tokens; the CuTe ``mamba3_step_fn`` would be faster but needs a Linux GPU
    pod). See ``mamba3-inference-params-carry-verdict``.

    SISO-only (``is_mimo=False``); MIMO needs the tilelang kernel, unavailable
    here -- ``load_mamba3_voice`` guards this and leaves stock forward alone for
    MIMO checkpoints.
    """
    import torch
    import torch.nn.functional as F
    from einops import rearrange

    from mamba_ssm.modules.mamba3 import heavy_tail_activation, mamba3_siso_combined

    assert not self.is_mimo, "_mamba3_siso_carry_forward is SISO-only"
    batch, seqlen, dim = u.shape

    angle_dt_state = ssm_state = k_state = v_state = None
    if inference_params is not None:
        inference_batch = (cu_seqlens.shape[0] - 1
                           if cu_seqlens is not None else batch)
        angle_dt_state, ssm_state, k_state, v_state = self._get_states_from_cache(
            inference_params, inference_batch)
    resume = inference_params is not None and inference_params.seqlen_offset > 0

    zxBCdtAtrap = self.in_proj(u)
    z, x, B, C, dd_dt, dd_A, trap, angles = torch.split(
        zxBCdtAtrap,
        [self.d_inner, self.d_inner,
         self.d_state * self.num_bc_heads * self.mimo_rank,
         self.d_state * self.num_bc_heads * self.mimo_rank,
         self.nheads, self.nheads, self.nheads, self.num_rope_angles],
        dim=-1)
    z = rearrange(z, "b l (h p) -> b l h p", p=self.headdim)
    x = rearrange(x, "b l (h p) -> b l h p", p=self.headdim)
    B = rearrange(B, "b l (r g n) -> b l r g n", r=self.mimo_rank, g=self.num_bc_heads)
    C = rearrange(C, "b l (r g n) -> b l r g n", r=self.mimo_rank, g=self.num_bc_heads)
    trap = rearrange(trap, "b l h -> b h l")

    _A = torch.clamp(-heavy_tail_activation(dd_A.to(torch.float32)),
                     max=-self.A_floor)
    DT = F.softplus(dd_dt + self.dt_bias)
    ADT = _A * DT
    DT = rearrange(DT, "b l n -> b n l")
    ADT = rearrange(ADT, "b l n -> b n l")
    angles = angles.unsqueeze(-2).expand(-1, -1, self.nheads, -1).to(torch.float32)

    B = self.B_norm(B)
    C = self.C_norm(C)

    input_states = ((angle_dt_state, ssm_state, k_state.squeeze(1), v_state)
                    if resume else None)
    y = mamba3_siso_combined(
        Q=C.squeeze(2), K=B.squeeze(2), V=x, ADT=ADT, DT=DT, Trap=trap,
        Q_bias=self.C_bias.squeeze(1), K_bias=self.B_bias.squeeze(1),
        Angles=angles, D=self.D, Z=z if not self.is_outproj_norm else None,
        chunk_size=self.chunk_size, Input_States=input_states,
        return_final_states=ssm_state is not None, cu_seqlens=cu_seqlens,
    )
    if ssm_state is not None:
        y, last_angle, last_state, last_k, last_v, *rest = y
        angle_dt_state.copy_(last_angle)
        ssm_state.copy_(last_state)
        k_state.copy_(last_k.unsqueeze(1))
        v_state.copy_(last_v)
    y = rearrange(y, "b l h p -> b l (h p)")
    if self.is_outproj_norm:
        z = rearrange(z, "b l h p -> b l (h p)")
        y = self.norm(y, z)
    out = self.out_proj(y.to(x.dtype))
    return out


class Mamba3Voice:
    """SSM-B: a real Mamba3 LM expands a retrieved blurb via continuation.

    Wraps the official ``mamba_ssm`` Mamba3-SISO checkpoint
    (``state-spaces/mamba3-siso-443m``) + the Llama-3.1 tokenizer. Unlike
    ``TokenLMVoice`` (the owned 7.9M SelectiveSSM, val ppl 177 -- see
    ``pondr-token-lm-ssm-result``), this is a real 443M LM -- the comparison that
    shows what a production-scale Mamba3 brings to the voice leg. Same
    ``Voice`` contract as ``TokenLMVoice``; selectable from ``runtime.py`` via
    ``fade_memory_voice_backend="mamba3"``.

    ``expand`` runs a correct O(n) decode: one prefill forward over the blurb
    seeds the recurrent state into an ``InferenceParams`` cache, then each new
    token is a single length-1 forward that resumes from the carried state.
    ``load_mamba3_voice`` patches ``Mamba3.forward`` with
    ``_mamba3_siso_carry_forward`` so the resume threads the cache into the
    EXACT Triton SISO combined kernel (``Input_States``) instead of the CuTe
    ``step()`` kernel (``None`` on this box). The Triton ``mamba3_siso_step``
    kernel is NOT used -- its approximations accumulate and collapse to a
    repetition attractor within a few tokens (see ``mamba3-inference-params-carry-verdict``).
    Research substrate; production swaps in the serving LLM as the voice.
    """

    def __init__(self, model, tokenizer, device: str = "cuda",
                 temperature: float = 0.7, top_p: float = 0.9,
                 seed: int = 0) -> None:
        self.model = model
        self.tokenizer = tokenizer
        self.device = device
        self.temperature = float(temperature)
        self.top_p = float(top_p)
        self.seed = int(seed)
        # Cross-turn carry state (exp #4): the per-conversation InferenceParams
        # kept alive across turns so Mamba3's recurrent state accumulates the
        # conversation. ``None`` until the first ``ingest_turn`` allocates it
        # (lazy -- a voice constructed without carry never touches the model).
        # ``ingest_turn`` is the ONLY writer; ``recall_from_carry`` is READ-ONLY
        # (clones into a throwaway). ``_carry_max`` bounds the pre-allocated
        # cache (Mamba3's allocate_inference_cache can't grow); set at first
        # ingest from FadeConfig.voice_carry_max_tokens.
        self._carry_inf = None          # InferenceParams (None = no carry yet)
        self._carry_seqlen = 0          # tokens consumed into the carried state
        self._carry_max = 0             # pre-allocated cache capacity

    def expand(self, blurb: str, max_new_tokens: int) -> str:
        import torch  # lazy: keeps the module importable without torch
        from mamba_ssm.utils.generation import InferenceParams

        if not blurb.strip():
            return blurb
        # Llama-3.1 tokenizer: encode adds BOS (model trained with it); decode
        # skips special tokens so the continuation is plain text.
        ids = self.tokenizer.encode(blurb)
        if not ids:
            return blurb
        prompt = torch.tensor([ids], dtype=torch.long, device=self.device)
        gen = (torch.Generator(device=self.device).manual_seed(self.seed)
               if self.temperature > 0 else None)
        eos = self.tokenizer.eos_token_id
        # O(n) decode: prefill seeds the recurrent state into the InferenceParams
        # cache; each new token is a length-1 forward that resumes from the
        # carried state (via the patched _mamba3_siso_carry_forward). One forward
        # per token, no growing-prefix re-forward.
        max_seqlen = len(ids) + max_new_tokens + 1
        inf = InferenceParams(max_seqlen=max_seqlen, max_batch_size=1)
        inf.key_value_memory_dict = self.model.allocate_inference_cache(
            1, max_seqlen)
        new_ids: list[int] = []
        with torch.inference_mode():
            out = self.model(prompt, inference_params=inf)
            logits = out.logits if hasattr(out, "logits") else out
            nxt = logits[0, -1].float()
            inf.seqlen_offset = len(ids)
            for _ in range(max_new_tokens):
                if self.temperature <= 0:
                    choice = int(nxt.argmax().item())
                else:
                    probs = torch.softmax(nxt / self.temperature, dim=-1)
                    if self.top_p < 1.0:
                        srt, idx = torch.sort(probs, descending=True)
                        cum = torch.cumsum(srt, dim=-1)
                        keep = (cum - srt) < self.top_p
                        keep[0] = True
                        mask = torch.zeros_like(probs)
                        mask.scatter_(0, idx[keep], srt[keep])
                        probs = mask / mask.sum()
                    choice = int(torch.multinomial(probs, 1, generator=gen).item())
                if choice == eos:
                    break
                new_ids.append(choice)
                tok = torch.tensor([[choice]], dtype=torch.long,
                                   device=self.device)
                out = self.model(tok, inference_params=inf)
                logits = out.logits if hasattr(out, "logits") else out
                nxt = logits[0, -1].float()
                inf.seqlen_offset += 1
        return self.tokenizer.decode(new_ids, skip_special_tokens=True)

    # -- cross-turn carry (exp #4) -----------------------------------
    def _ensure_carry(self, max_tokens: int) -> None:
        """Allocate the carried InferenceParams cache once (idempotent).

        ``allocate_inference_cache`` pre-allocates a fixed ``max_seqlen`` slab
        that cannot grow, so the budget is fixed at first ingest. A decode
        margin (64) leaves room for ``recall_from_carry``'s cue+decode to fit
        within the same slab on the throwaway clone (the clone reuses this
        ``max_seqlen``). ``max_tokens`` is ``FadeConfig.voice_carry_max_tokens``.
        """
        import torch  # noqa: F401 -- lazy: keeps the module importable w/o torch
        from mamba_ssm.utils.generation import InferenceParams

        if self._carry_inf is not None:
            return
        self._carry_max = int(max_tokens) + 64  # +decode margin for the clone
        inf = InferenceParams(max_seqlen=self._carry_max, max_batch_size=1)
        inf.key_value_memory_dict = self.model.allocate_inference_cache(
            1, self._carry_max)
        inf.seqlen_offset = 0
        self._carry_inf = inf

    def ingest_turn(self, text: str, max_tokens: int = 2048) -> int:
        """Forward one turn's tokens through the carried state (the only writer).

        Seeds the carried ``InferenceParams`` on the first call (allocates the
        cache to ``max_tokens + 64``), then advances the recurrent state by the
        turn's tokens. No decode -- this consumes the conversation into the SSM
        state, mirroring the probe's ``_forward_chunk`` (one forward, then
        ``seqlen_offset += len(ids)``). Returns the number of tokens actually
        consumed (0 when the carry is saturated or the turn is empty).

        The turn is truncated to fit the remaining budget: once the carried
        state reaches ``max_tokens`` the within-window memory is full, and
        beyond-window long-term is WaveDB's job (exp #4: carry degrades past the
        ~2048-token training-ctx ceiling together with continuous). Saturating
        and stopping is the CORRECT behavior, not a hack.
        """
        import torch
        if not text or not text.strip():
            return 0
        self._ensure_carry(max_tokens)
        ids = self.tokenizer.encode(text, add_special_tokens=False)
        if not ids:
            return 0
        # Truncate to the remaining budget (stop advancing once saturated).
        room = self._carry_max - self._carry_seqlen
        if room <= 0:
            return 0  # saturated -- within-window memory full
        ids = ids[:room]
        cur = torch.tensor([ids], dtype=torch.long, device=self.device)
        with torch.inference_mode():
            self.model(cur, inference_params=self._carry_inf)
        self._carry_inf.seqlen_offset += len(ids)
        self._carry_seqlen += len(ids)
        return len(ids)

    def recall_from_carry(self, cue: str, max_new_tokens: int = 64) -> str:
        """READ-ONLY recall: cue the carried state and greedy-decode a continuation.

        Clones the carried cache into a throwaway ``InferenceParams``
        (``seqlen_offset`` = carried N), forwards the cue, then greedy-decodes
        ``max_new_tokens`` (length-1 forwards via the patched
        ``_mamba3_siso_carry_forward``). The throwaway is discarded -- the
        carried state is NEVER mutated by recall (the actual turn is ingested
        after recall, as today; ``ingest_turn`` stays the sole writer). Mirrors
        the probe's ``complete_carry`` final turn, but non-mutating.

        Returns ``""`` when there is no carried state yet (turn-1 recall: nothing
        to carry) or the cue is empty. Greedy (temp 0) -- a recall, not a sample.
        """
        import torch
        from mamba_ssm.utils.generation import InferenceParams

        if self._carry_inf is None or self._carry_seqlen == 0:
            return ""
        if not cue or not cue.strip():
            return ""
        cue_ids = self.tokenizer.encode(cue, add_special_tokens=False)
        if not cue_ids:
            return ""
        eos = self.tokenizer.eos_token_id
        # Clone the carried cache (read-only): a fresh InferenceParams sharing
        # nothing with the carried state but its starting point. Each per-layer
        # entry is a 4-tuple of state tensors (angle_dt, ssm, k, v -- see
        # ``Mamba3._get_states_from_cache``); cloning them means the throwaway's
        # forward writes back via ``.copy_()`` into the CLONES, so the carried
        # state is never mutated (the read-only invariant).
        throw = InferenceParams(max_seqlen=self._carry_max, max_batch_size=1)
        carried = self._carry_inf.key_value_memory_dict
        throw.key_value_memory_dict = {
            layer: [t.clone() for t in cache]
            for layer, cache in carried.items()
        }
        throw.seqlen_offset = self._carry_seqlen  # resume from carried point
        # Clamp the decode so the throwaway never exceeds its slab.
        gen = min(int(max_new_tokens),
                  self._carry_max - throw.seqlen_offset - len(cue_ids))
        if gen <= 0:
            return ""
        out_ids: list[int] = []
        with torch.inference_mode():
            cur = torch.tensor([cue_ids], dtype=torch.long, device=self.device)
            out = self.model(cur, inference_params=throw)
            logits = out.logits if hasattr(out, "logits") else out
            nxt = logits[0, -1].float()
            throw.seqlen_offset += len(cue_ids)
            for _ in range(gen):
                choice = int(nxt.argmax().item())
                if choice == eos:
                    break
                out_ids.append(choice)
                tok = torch.tensor([[choice]], dtype=torch.long,
                                   device=self.device)
                out = self.model(tok, inference_params=throw)
                logits = out.logits if hasattr(out, "logits") else out
                nxt = logits[0, -1].float()
                throw.seqlen_offset += 1
        return self.tokenizer.decode(out_ids, skip_special_tokens=True)

    def reset_carry(self) -> None:
        """Drop the carried state (``FadeMemory.reset`` calls this for a fresh
        session). The next ``ingest_turn`` re-allocates."""
        self._carry_inf = None
        self._carry_seqlen = 0
        self._carry_max = 0


def load_mamba3_voice(model_id: str, tokenizer_id: str, device: str = "auto",
                      temperature: float = 0.7, top_p: float = 0.9,
                      seed: int = 0) -> Mamba3Voice:
    """Load a pretrained Mamba3-SISO LM as the SSM-B voice. Lazy imports.

    ``model_id``: a ``state-spaces/mamba3-siso-*`` checkpoint (443m / 893m /
    1.5b). ``tokenizer_id``: a Llama-3.1 tokenizer repo -- the official
    ``meta-llama/Llama-3.1-8B`` is gated; ``NousResearch/Meta-Llama-3.1-8B`` is
    the ungated mirror. The model is frozen (``eval()``); the voice expands, it
    does not train.

    ``device`` accepts ``"auto"`` (resolve to cuda if available, else cpu), like
    ``load_token_lm_voice``. The Mamba3 Triton SISO kernel is CUDA-only, so
    ``"cpu"`` will fail at the first ``forward()`` -- ``"auto"`` is right.

    Self-contained: if ``CC`` is unset and the triton-windows bundled TinyCC is
    present, sets ``CC`` to it so the Triton JIT uses TinyCC instead of the
    env-MSVC ``cl`` that breaks on ``/std:c11``. Without this the caller must
    export ``CC=<.../tcc.exe>`` before invoking the serve path. The official
    MIMO (``mamba3-mimo-*``) checkpoints need the tilelang kernel, which is
    unavailable here -- use the SISO checkpoints.
    """
    import os

    if os.environ.get("CC") is None:
        tcc = _bundled_tcc()
        if tcc is not None:
            os.environ.setdefault("CC", tcc)

    import torch
    from transformers import AutoTokenizer

    from mamba_ssm.models.mixer_seq_simple import MambaLMHeadModel

    if device == "auto":
        device = "cuda" if torch.cuda.is_available() else "cpu"
    model = MambaLMHeadModel.from_pretrained(
        model_id, device=device, dtype=torch.bfloat16)
    model.eval()
    tok = AutoTokenizer.from_pretrained(tokenizer_id)
    # Patch the per-layer Mamba3 forward with the carry-correct SISO variant so
    # the InferenceParams cache is threaded into the EXACT Triton combined kernel
    # on resume (stock routes resume to the CuTe step() kernel, None on this box,
    # and hardcodes Input_States=None so the cache is written but never read).
    # SISO checkpoints only; MIMO would need the tilelang kernel (unavailable here).
    from mamba_ssm.modules.mamba3 import Mamba3
    if not getattr(model.backbone.layers[0].mixer, "is_mimo", False):
        Mamba3.forward = _mamba3_siso_carry_forward
    return Mamba3Voice(model, tok, device, temperature, top_p, seed)


def bge_embedder() -> Embedder:
    """The frozen bge-small-en-v1.5 embedder (384-d). Lazy import."""
    from src.retrieval.vector_search import _sentence_transformers_embedder

    return _sentence_transformers_embedder()


# ----------------------------------------------------------------- the recall
@dataclass
class Recall:
    """One anchor's recall result at the current stream step."""

    anchor_id: int
    regime: int                 # REGIME_* label
    cos: float                  # cos(state_t, bge(anchor_i)) -- the free router
    content: str                # verbatim text (R1) / expanded blurb (R3) / marker (R4)
    blurb: Optional[str] = None  # the retrieved blurb before expansion (R3 only)
    cos_q: float = 0.0          # cos(bge(prompt), bge(anchor)) -- prompt relevance;
                                # the within-regime drop key for the A4 budget cascade
                                # (the free router ``cos`` is recoverability, ~constant
                                # within a regime, so it is useless as a tiebreak).
                                # Surfaced from ``BlurbStore.retrieve`` in ``recall``
                                # (was discarded pre-A4); 0.0 when unset.


# ----------------------------------------------------------------- FadeMemory
class FadeMemory:
    """The dual-SSM fade memory (Stage 1).

    Holds SSM-A (``VectorCarrySSM``), the blurb store, the ring (recency verbatim
    window), and an injected voice (SSM-B). The router is the free cosine
    ``e(i,t) = 1 - cos(state_t, bge(anchor_i))`` -- no trained head, no ridge fit
    (the channel is in bge space). ``ingest`` streams a chunk; ``recall_anchor``
    routes one anchor to its regime; ``recall`` routes a query's relevant past
    anchors. ``voice`` is optional: when ``None``, Regime 3 returns the retrieved
    blurb verbatim (the built-in passthrough -- no separate stub voice class), so
    the memory runs without loading the token-LM; production wires the real
    token-LM (``load_token_lm_voice``) for continuation expansion.
    """

    def __init__(self, cfg: FadeConfig, embedder: Embedder,
                 voice: Optional[Voice] = None, dim: int = 384) -> None:
        self.cfg = cfg
        self.embedder = embedder
        self.voice = voice
        self.dim = int(dim)
        self.ssm_a = VectorCarrySSM(self.dim, cfg.decay, cfg.write_gate)
        self.blurbs = BlurbStore(self.dim)
        self.ring: deque[int] = deque(maxlen=cfg.ring_capacity)
        self._next_id = 0
        # Consolidation state (the gist-on-forgetting loop). ``consolidation_counts``
        # tracks gist-of-gist depth per anchor (capped by ``max_depth`` in
        # ``fading_anchors``); ``_prior_gists`` holds the prior narrative fed back
        # to the gister on the next pass (the prior-baseline-merge that preserves
        # fidelity across compressions). Empty until a sweep consolidates an anchor.
        self.consolidation_counts: dict[int, int] = {}
        self._prior_gists: dict[int, str] = {}

    # -- ingestion -----------------------------------------------------
    def ingest(self, chunk_text: str, blurb_text: Optional[str] = None) -> int:
        """Encode the chunk, step SSM-A, store the blurb, push to the ring.

        Returns the anchor_id (the chunk's position in the stream). The bge
        vector is the chunk's OWN frozen embedding (no teacher LLM -- bge is
        frozen); it is what SSM-A carries and what the blurb is keyed by.

        ``chunk_text`` is the EMBED HANDLE -- the string the bge vector is
        computed from (and what SSM-A carries / what the blurb is keyed by).
        ``blurb_text`` (optional) is the RECALLED CONTENT -- the text stored
        as the blurb and returned on R1/R3 recall. When ``None`` (the default,
        and every existing caller) the blurb is ``chunk_text[:blurb_chars]`` --
        byte-identical to the one-arg path. The split mirrors the production
        code-ingestion design: embed a prose summary of a function (the handle
        that ranks against prose queries) but recall the raw source (the thing
        the user actually wants back). The two must be allowed to differ so a
        "gist" of code can be a raw excerpt, not a purpose-summary."""
        anchor_id = self._next_id
        # The collapse (exp #4 follow-on, default OFF): when on, the SSM-A path is
        # SUPPRESSED -- no anchor is created (no bge vector, no blurb, no ring
        # slot), so the carried Mamba3 state is the SOLE within-window memory. The
        # carry ingest below runs either way (it is the within-window leg; collapse
        # makes it the ONLY leg). Returns -1 (the carry sentinel, matching
        # ``Recall(anchor_id=-1)``) -- under collapse there is no SSM-A anchor_id
        # to return; the value is unused by the orchestrator (it keys ``ingest`` on
        # the return only to advance its own counters, which the collapse path does
        # not touch). When off, byte-identical to today: encode, step SSM-A, store
        # the blurb, push to the ring.
        if self.cfg.collapse:
            anchor_id = -1
        else:
            self._next_id += 1
            vec = self._encode_one(chunk_text)     # [dim] bge (unnormalized ok)
            self.ssm_a.step(vec)                    # the fade leg advances
            blurb_src = blurb_text if blurb_text is not None else chunk_text
            blurb = blurb_src[: self.cfg.blurb_chars]
            self.blurbs.add(anchor_id, vec, blurb)  # keyed by bge (the handle)
            self.ring.append(anchor_id)             # recency verbatim window
        # Cross-turn carry (exp #4, additive, default OFF): forward the turn
        # through the carried Mamba3 state too, so its recurrent state accumulates
        # the conversation. ``ingest_turn`` is the sole writer; ``chunk_text`` is
        # the full turn (the orchestrator passes the joined "User: ... \nAssistant:
        # ..." text). Best-effort: a carry failure is swallowed so the SSM-A ingest
        # that just succeeded is not masked. No-op when ``voice_carry`` is off or
        # the voice is not a ``CarryVoice`` (``hasattr`` guard). Under collapse this
        # is the ONLY ingest path (the SSM-A branch above is skipped).
        if self.cfg.voice_carry and hasattr(self.voice, "ingest_turn"):
            try:
                self.voice.ingest_turn(
                    chunk_text, max_tokens=self.cfg.voice_carry_max_tokens)
            except Exception:  # noqa: BLE001 - never break the SSM-A ingest
                pass
        return anchor_id

    def _encode_one(self, text: str) -> np.ndarray:
        raw = self.embedder.encode([text])[0]
        return np.asarray(raw, dtype=np.float32)

    # -- the free router ----------------------------------------------
    def _recoverability(self, anchor_id: int) -> Optional[float]:
        """``cos(state_t, bge(anchor_i))`` -- the free recoverability signal.

        High = the anchor is still in the state (low e -> Regime 1); low = faded
        (high e -> Regime 3/4). None if the anchor is not in the store."""
        v = self.blurbs.vector(anchor_id)
        if v is None:
            return None
        q = self.ssm_a.query()  # L2-normalized state
        return float(np.dot(q, v))  # both normalized -> cosine

    # -- per-anchor regime dispatch -----------------------------------
    def recall_anchor(self, anchor_id: int) -> Optional[Recall]:
        """Route one anchor by its recoverability -> the form the recall takes.

        Returns None if the anchor is unknown. The ring provides true verbatim
        for the recency window independent of the state's fade; the cosine
        router handles everything older (gist / forgotten)."""
        cos_i = self._recoverability(anchor_id)
        if cos_i is None:
            return None
        cfg = self.cfg
        in_ring = anchor_id in self.ring
        # Regime 1: recency window (ring) OR state still fresh.
        if in_ring or cos_i >= cfg.cos_ring:
            return Recall(anchor_id, REGIME_VERBATIM, cos_i,
                          content=self._verbatim(anchor_id))
        # Regime 2 (Transformer fill-holes) is deprioritized (probe #31: thin).
        # When enabled, medium-e is labeled FILL; without the Stage-2
        # ``CrossSlotTransformerZHead`` wired, the honest degraded behavior is the
        # same retrieve+expand Regime 3 does (the label is the dispatch decision;
        # the Transformer readout is the Stage-2 differentiator that replaces
        # this). When disabled (default), medium-e falls through to Regime 3.
        if cfg.regime2_enabled and cos_i >= cfg.cos_gist:
            return self._retrieve_and_expand(anchor_id, cos_i, REGIME_FILL)
        # Regime 3: faded but the address survives -> retrieve + expand.
        if cos_i >= cfg.cos_gist:
            return self._retrieve_and_expand(anchor_id, cos_i, REGIME_GIST)
        # Regime 4: tip-of-tongue floor -> forgotten (do not confabulate).
        return Recall(anchor_id, REGIME_FORGOTTEN, cos_i, content="[forgotten]")

    def _verbatim(self, anchor_id: int) -> str:
        # The ring is the preferred verbatim source; the blurb store holds the
        # same text for every anchor (the source of truth), so an anchor evicted
        # from the ring but still state-fresh (cos >= cos_ring) still returns its
        # exact text.
        return self.blurbs.text(anchor_id) or ""

    def _retrieve_and_expand(self, anchor_id: int, cos_i: float,
                             regime: int) -> Recall:
        # Regime 3 (and the degraded Regime 2): the anchor's ADDRESS survives
        # (cos_i >= cos_gist = the state still carries a recoverable trace of
        # it), so retrieve the anchor's OWN blurb and let SSM-B expand it. The
        # state's role is the recoverability SIGNAL (cos -> regime), NOT the
        # retrieval key: a state-closest blurb is dominated by the most-recent
        # chunk and drifts to wrong-topic content across a mixed-domain
        # session (the R3 content-drift found in the serve REPL validation --
        # docs/fade-serve-validation-result.md; the within-domain "state
        # retrieves a sibling" of probe #32 only holds when the state is still
        # dominated by the anchor's domain). The fade is expressed through the
        # SSM-B expansion (paraphrase) + the regime label (lower confidence),
        # not through retrieving a sibling. If the anchor's blurb is gone,
        # degrade to R4. (Mirrors ``_verbatim`` -- the blurb store is the source
        # of truth, addressed by anchor_id.)
        #
        # NOTE: once the consolidation loop (``consolidate``) has gisted this
        # anchor, the stored blurb IS the narrative gist (not the verbatim), so
        # R3 returns a REAL gist -- the regime label and the content finally
        # agree. Before consolidation, R3 returns the verbatim blurb (the label
        # is aspirational). Either way the anchor's own blurb is the content.
        blurb = self.blurbs.text(anchor_id)
        if blurb is None:
            return Recall(anchor_id, REGIME_FORGOTTEN, cos_i, content="[forgotten]")
        # ``voice is None`` -> the built-in passthrough: return the anchor's
        # blurb verbatim (no token-LM loaded). Production wires ``TokenLMVoice``
        # for continuation expansion; tests + the Phase-A serve path run
        # passthrough.
        if self.voice is None:
            return Recall(anchor_id, regime, cos_i, content=blurb, blurb=blurb)
        expanded = self.voice.expand(blurb, self.cfg.expand_tokens)
        return Recall(anchor_id, regime, cos_i, content=expanded, blurb=blurb)

    # -- query-driven recall ------------------------------------------
    def recall(self, query_text: str, top_k: int = 5) -> list[Recall]:
        """Recall past content relevant to ``query_text``, each in the form its
        recency dictates.

        Step 1: retrieve candidate anchors by the query's bge vs the blurb store
        (relevance -- standard semantic search). Step 2: route each candidate by
        the free cosine router (recency -> verbatim / gist / forgotten). Returns
        the routed recalls, best-relevance first."""
        q = self._encode_one(query_text)
        out: list[Recall] = []
        # The collapse (exp #4 follow-on, default OFF): when on, SKIP the SSM-A
        # regime path entirely -- no BlurbStore retrieve, no per-anchor routing.
        # The within-window recall is UNCONDITIONAL carry (the block below); there
        # is nothing to route (no SSM-A state -> no cosine-vs-anchor signal). When
        # off, byte-identical to today: retrieve candidates, route each by the
        # free cosine router.
        if not self.cfg.collapse:
            candidates = self.blurbs.retrieve(q, k=top_k)  # (anchor_id, cos_q, text)
            for anchor_id, cos_q, _ in candidates:
                r = self.recall_anchor(anchor_id)
                if r is not None:
                    # A4: surface the prompt-relevance cosine (was discarded pre-A4)
                    # so ``format_fade_block``'s budget cascade can drop the
                    # least-prompt-relevant recall within a regime first.
                    r.cos_q = cos_q
                    out.append(r)
        # Cross-turn carry (exp #4, additive, default OFF): cue the carried
        # conversation state and PREPEND a within-window recall. Skipped when
        # ``voice_carry`` is off, the voice is not a ``CarryVoice``, or no turn has
        # been ingested yet (turn-1 recall: nothing to carry -- ``_carry_seqlen``
        # is 0). The carried recall is a synthetic anchor (id = -1) routed to
        # ``REGIME_CARRY``; ``cos=1.0`` ranks it first and ``cos_q=0.0`` is inert
        # (it has no bge-vs-anchor signal -- Mamba3's state is not a bge vector).
        # Best-effort: a decode failure yields no carried recall. Under collapse
        # this is the ONLY recall path -- ``out`` is just ``[carry]`` (or ``[]`` on
        # turn 1 / an empty decode). ``q`` is computed above even under collapse
        # (cheap, one encode) and is simply unused -- kept for a single-branch read
        # and to avoid a divergence that a ``if not collapse: q = ...`` would invite.
        if self.cfg.voice_carry and hasattr(self.voice, "recall_from_carry") \
                and getattr(self.voice, "_carry_seqlen", 0) > 0:
            # Cue engineering: apply the cue template (default "{cue}" is
            # IDENTITY -- skip the format call entirely so the hot path is
            # byte-identical to flag-off; only a non-default template reaches
            # ``recall_from_carry`` reshaped). The template receives ``{cue}`` =
            # the user prompt. A misconfigured template (a placeholder other
            # than ``{cue}``, e.g. ``{foo}``) ``KeyError``s at format time; that
            # is INSIDE the try/except below -> swallowed -> no carry recall
            # (the safest failure mode; the regime recalls survive).
            try:
                cue = query_text
                if self.cfg.voice_carry_cue_template != "{cue}":
                    cue = self.cfg.voice_carry_cue_template.format(cue=query_text)
                content = self.voice.recall_from_carry(
                    cue, max_new_tokens=self.cfg.voice_carry_recall_tokens)
            except Exception:  # noqa: BLE001 - never break the regime recalls
                content = ""
            if content.strip():
                out.insert(0, Recall(anchor_id=-1, regime=REGIME_CARRY,
                                     cos=1.0, content=content))
        return out

    # -- lifecycle -----------------------------------------------------
    def reset(self) -> None:
        """Zero the state, clear the blurb store and ring (a fresh session)."""
        self.ssm_a.reset()
        self.blurbs = BlurbStore(self.dim)
        self.ring.clear()
        self._next_id = 0
        self.consolidation_counts = {}
        self._prior_gists = {}
        # Drop the carried Mamba3 state too (exp #4) so a reset session does not
        # bleed the prior conversation's recurrent state. No-op for a non-carry
        # voice (``hasattr`` guard).
        if hasattr(self.voice, "reset_carry"):
            self.voice.reset_carry()

    # -- consolidation (the gist-on-forgetting loop) -------------------
    def prior_gist(self, anchor_id: int) -> Optional[str]:
        """The anchor's current consolidated narrative (None until its first
        consolidation). Fed back to the gister on the next pass so gist-of-gist
        is fidelity-preserving (prior-baseline-merge)."""
        return self._prior_gists.get(anchor_id)

    def consolidation_count(self, anchor_id: int) -> int:
        """How many times this anchor has been consolidated (0 = verbatim)."""
        return self.consolidation_counts.get(anchor_id, 0)

    def fading_anchors(self, epsilon: float = 0.03, max_depth: int = 3,
                       max_per_tick: int = 8) -> list[int]:
        """Anchors a consolidation sweep should gist, most-faded-first.

        The automatic threshold trigger: an anchor is eligible when its
        recoverability has crossed the R3->R4 boundary -- ``cos < cos_gist +
        epsilon`` (the ``+epsilon`` hysteresis catches anchors just as they cross
        -- the user's "reaches the point where it can't be recalled") -- AND it
        is not in the ring (verbatim window; never consolidate fresh recall),
        AND it is under the gist-of-gist depth cap (``max_depth``; beyond it the
        anchor stays R4 -- the real forgotten -> long-term-pull floor), AND its
        blurb still exists. Capped at ``max_per_tick`` to bound queue growth.
        Read-only on the memory -- safe for the worker's ``tick`` to call during
        a foreground query (the mutation happens later in ``consolidate``,
        gated on the foreground event).
        """
        threshold = self.cfg.cos_gist + epsilon
        out: list[tuple[float, int]] = []
        for aid in self.blurbs._ids:
            if aid in self.ring:
                continue
            if self.consolidation_counts.get(aid, 0) >= max_depth:
                continue
            if self.blurbs.text(aid) is None:
                continue
            cos_i = self._recoverability(aid)
            if cos_i is None or cos_i >= threshold:
                continue
            out.append((cos_i, aid))
        out.sort(key=lambda ca: ca[0])  # most-faded (lowest cos) first
        return [aid for _, aid in out[:max_per_tick]]

    def consolidate(self, anchor_id: int, gist: "StructuredGist") -> float:
        """Apply a structured gist IN PLACE -- the compression step.

        The original anchor BECOMES its gist (the user's "update the excerpt"):
        the blurb is re-keyed to ``bge(narrative)`` and the recalled text becomes
        the narrative; SSM-A is re-stepped with ``bge(narrative)`` (the "add them
        to the ssm" step -- fresh recency, the anchor jumps R4 -> R1); the ring
        position is refreshed (no duplicate); the facts sidecar is staged; the
        consolidation count + prior-gist are recorded for the next gist-of-gist
        pass. This is the INVERSE of LRU: the gist REPLACES the verbatim (a
        compressed form), not a recency refresh of the same text -- so the fade
        still progresses (fidelity degrades gist-of-gist over sweeps), and R4
        still fires for anchors the sweep never reaches.

        Returns the new ``cos(state, bge(narrative))`` (for observability -- it
        should be high, R1, since the gist's vector is now the most-recent SSM
        write). Raises ``KeyError`` if the anchor is unknown.
        """
        vec = self._encode_one(gist.narrative)
        self.blurbs.update(
            anchor_id, vec,
            gist.narrative[: self.cfg.blurb_chars],
            facts=list(gist.facts) + list(gist.state_assertions),
        )
        self.ssm_a.step(vec)  # fresh recency -- the gist is now recallable
        # Refresh the ring position (no duplicate): the gist is "recent" again.
        if anchor_id in self.ring:
            self.ring.remove(anchor_id)
        self.ring.append(anchor_id)
        self._prior_gists[anchor_id] = gist.narrative
        self.consolidation_counts[anchor_id] = (
            self.consolidation_counts.get(anchor_id, 0) + 1
        )
        return self._recoverability(anchor_id) or 0.0