"""Episode data model — the atomic unit of episodic memory."""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional


@dataclass
class Episode:
    """One complete conversational exchange (user message + assistant response).

    The atomic unit of encoding: the smallest unit that contains everything
    needed for retrieval — who, what, how felt, what decided, what next.

    Content (``summary``, ``full_text``, ``timestamp``) is the "neocortical"
    payload stored in the WaveDB HBTrie; structure (entities/topics/tones/
    decisions/relations/follows) is the "hippocampal index" stored as triples in
    the WaveDB Graph layer. See ``store.py``.
    """

    id: str
    timestamp: str
    summary: str
    full_text: str
    entities: list[str] = field(default_factory=list)
    # A3: entity span -> seed ontology class (Person/Project/Technology) for
    # emitting ``(E:entity, instanceOf, Class)`` typing edges. Empty for
    # pre-A3 episodes + open-discovery entities (untyped until Bonsai
    # promotion); the encoder emits instanceOf only for entries present here.
    entity_classes: dict[str, str] = field(default_factory=dict)
    topics: list[str] = field(default_factory=list)
    tones: list[str] = field(default_factory=list)
    decisions: list[str] = field(default_factory=list)
    relations: list[dict] = field(default_factory=list)
    # ── Phase 3c: entity-state assertions ──
    # Explicit ``entity -> value`` claims (``{"entity", "value"}``) lifted from
    # the deterministic normalizer (src/encoding/assertion_extractor.py) UNION
    # Bonsai ``has_state`` relations. These are the production writer of
    # ``(E:entity, state, literal)`` edges (the A2 anomaly-resolver input);
    # provenance defaults to the carrying episode (the store writes
    # ``asserted_by=episode_id`` / ``asserted_at=timestamp`` on each edge's
    # sidecar). Empty on pre-Phase-3c episodes + text with no explicit state
    # claims -- the cold-start no-op (D6).
    state_assertions: list[dict] = field(default_factory=list)
    follows: Optional[str] = None
    # User/session scope for global chat history. None = unscoped (backward-
    # compatible with the single-session Phase 1a model). When set, the store
    # writes (U:user, has_session, S:session), (S:session, has_episode, ep),
    # (ep, in_session, S:session), (ep, at_time, <ts>), and the session's
    # started_at/ended_at + follows_session chain. See ontology.py.
    user_id: Optional[str] = None
    session_id: Optional[str] = None
    # Provenance (2026-07-14): two orthogonal axes so the system never
    # confuses a real user-stated fact with the model's own generated output.
    #   origin  -- episode-level SOURCE. "corpus" = ingested real conversation
    #              (default, preserves all pre-provenance behavior); "live" =
    #              orchestrator-encoded, assistant turn generated by our LLM.
    #   messages -- per-segment CONTENT KIND, OpenAI Chat Completions role
    #              vocabulary: [{"role": "system"|"developer"|"user"|
    #              "assistant"|"tool", "content": str, optional "tool_call_id",
    #              "name"}]. None on pre-provenance episodes (consumers fall
    #              back to full_text). Today only user+assistant are populated
    #              for a live exchange; system/tool/tool_call are reserved.
    origin: str = "corpus"
    messages: Optional[list[dict]] = None
    salience: float = 0.5
    state: str = "current"
    validity_start: Optional[str] = None
    validity_end: Optional[str] = None

    # ── Downstream-system fields (populated by Phase 1a, read by Phase 2-4) ──
    # Present from the start so the store schema never has to migrate later.
    # Phase 1a writes safe defaults; later phases update them on retrieval /
    # consolidation. Phase 1a persists retrieval_count / ltp_phase /
    # utility_decay_rate; the rest are reserved for Phase 3+ to populate.
    retrieval_count: int = 0
    ltp_phase: str = "early"  # "early" | "late" — long-term potentiation stage
    consolidation_window_start: Optional[str] = None
    utility_decay_rate: float = 0.01
    retrieval_timestamps: list[str] = field(default_factory=list)
    saturation_flags: int = 0

    # ── Phase 1b: semantic embedding of the summary for FAISS vector search ──
    # None until the embedding backfill (scripts/build_vector_index.py) populates
    # it; the store persists it as JSON under content/ep/{id}/embedding when set.
    summary_embedding: Optional[list[float]] = None

    def __post_init__(self) -> None:
        # A fact's validity begins when the episode was encoded. Reconsolidation
        # sets validity_end when a newer episode supersedes this one — the old
        # version is preserved (MVCC), just not returned by default queries.
        if self.validity_start is None:
            self.validity_start = self.timestamp

    @staticmethod
    def _join_messages(messages: list[dict]) -> str:
        """Render role-tagged segments as the flat ``full_text`` storage form.

        ``"{Role}: {content}"`` per segment, newline-joined -- byte-identical
        to the legacy ``"User: {u}\\nAssistant: {a}"`` for a two-turn user/
        assistant exchange. One way to build ``full_text`` so retrieval/GNN/
        tests that read ``text`` are unchanged regardless of which
        constructor produced the episode.
        """
        return "\n".join(
            f"{m.get('role', 'user').capitalize()}: {m.get('content', '')}"
            for m in messages
        )

    @staticmethod
    def _assistant_summary(messages: list[dict]) -> str:
        """First 200 chars of the last assistant segment's content (+ ``...``).

        Falls back to the last non-empty segment's content when no assistant
        segment has content, so the summary is never empty for a non-empty
        exchange. An empty summary makes the episode write-only --
        ``HippocampalStore.get_episode`` returns ``None`` when the stored
        summary is empty, so the episode could not be read back. The live path
        never hits this (the orchestrator skips encoding when the response is
        empty), but ``from_messages`` callers passing a system/tool-only
        message set are protected.
        """
        assistant_content = next(
            (m.get("content", "") for m in reversed(messages)
             if m.get("role") == "assistant" and m.get("content", "")),
            "",
        )
        if not assistant_content:
            # No assistant content -- fall back to the last non-empty segment
            # so the episode stays readable.
            assistant_content = next(
                (m.get("content", "") for m in reversed(messages)
                 if m.get("content", "")),
                "",
            )
        summary = assistant_content[:200]
        if len(assistant_content) > 200:
            summary += "..."
        return summary

    @classmethod
    def from_extraction(
        cls,
        episode_id: str,
        user_message: str,
        assistant_response: str,
        extracted: dict,
        relations: list[dict],
        follows: Optional[str] = None,
        timestamp: Optional[str] = None,
        user_id: Optional[str] = None,
        session_id: Optional[str] = None,
        origin: str = "corpus",
    ) -> "Episode":
        """Create an Episode from extraction results.

        Args:
            episode_id: Stable id (e.g. ``ep_0001``).
            user_message: The user side of the turn.
            assistant_response: The assistant side of the turn.
            extracted: Output of ``GLiNERExtractor.extract`` — keys
                ``entities`` / ``topics`` / ``tones`` / ``decisions`` / ``discovered``.
            relations: Output of ``BonsaiRelationExtractor.extract`` — list of
                ``{"subject", "predicate", "object"}`` triples.
            follows: Id of the previous episode in the conversation chain.
            timestamp: ISO timestamp; defaults to now (override for tests).
            user_id: Optional user scope.
            session_id: Optional session scope.
            origin: Episode source — ``"corpus"`` (default; ingested real
                conversation) or ``"live"`` (orchestrator-encoded).
        """
        messages = [
            {"role": "user", "content": user_message},
            {"role": "assistant", "content": assistant_response},
        ]
        full_text = cls._join_messages(messages)
        if timestamp is None:
            timestamp = datetime.now().isoformat()
        summary = cls._assistant_summary(messages)

        return cls(
            id=episode_id,
            timestamp=timestamp,
            summary=summary,
            full_text=full_text,
            entities=extracted.get("entities", []),
            entity_classes=extracted.get("entity_classes", {}),
            topics=extracted.get("topics", []),
            tones=extracted.get("tones", []),
            decisions=extracted.get("decisions", []),
            relations=relations,
            follows=follows,
            user_id=user_id,
            session_id=session_id,
            origin=origin,
            messages=messages,
        )

    @classmethod
    def from_messages(
        cls,
        episode_id: str,
        messages: list[dict],
        extracted: dict,
        relations: list[dict],
        follows: Optional[str] = None,
        timestamp: Optional[str] = None,
        user_id: Optional[str] = None,
        session_id: Optional[str] = None,
        origin: str = "corpus",
    ) -> "Episode":
        """Create an Episode from already-role-tagged segments (the live path).

        ``messages`` is the OpenAI Chat Completions shape (``{role, content,
        ...}``) -- the same shape the orchestrator receives as
        ``conversation_history``. ``full_text`` is derived by joining the
        segments so the corpus and live paths share one storage form. The
        summary is the last assistant segment's gist.

        Args:
            episode_id: Stable id (e.g. ``ep_0001``).
            messages: Role-tagged segments (``system``/``developer``/``user``/
                ``assistant``/``tool``).
            extracted: Output of ``GLiNERExtractor.extract``.
            relations: Output of ``BonsaiRelationExtractor.extract``.
            follows: Id of the previous episode in the conversation chain.
            timestamp: ISO timestamp; defaults to now (override for tests).
            user_id: Optional user scope.
            session_id: Optional session scope.
            origin: Episode source — ``"corpus"`` or ``"live"``.
        """
        full_text = cls._join_messages(messages)
        if timestamp is None:
            timestamp = datetime.now().isoformat()
        summary = cls._assistant_summary(messages)

        return cls(
            id=episode_id,
            timestamp=timestamp,
            summary=summary,
            full_text=full_text,
            entities=extracted.get("entities", []),
            entity_classes=extracted.get("entity_classes", {}),
            topics=extracted.get("topics", []),
            tones=extracted.get("tones", []),
            decisions=extracted.get("decisions", []),
            relations=relations,
            follows=follows,
            user_id=user_id,
            session_id=session_id,
            origin=origin,
            messages=list(messages),
        )